spring.application.name=hw23hogwarts
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username= student
spring.datasource.password= chocolatefrog

spring.jpa.hibernate.ddl-auto= update